package com.bloodnet.model;

public class TblFatherSon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.f_human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String fHumanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.s_human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String sHumanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.user_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.s_sex_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String sSexDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.delflg
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.create_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.create_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.create_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.update_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.update_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_father_son.update_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.f_human_id
     *
     * @return the value of tbl_father_son.f_human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getfHumanId() {
        return fHumanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.f_human_id
     *
     * @param fHumanId the value for tbl_father_son.f_human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setfHumanId(String fHumanId) {
        this.fHumanId = fHumanId == null ? null : fHumanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.s_human_id
     *
     * @return the value of tbl_father_son.s_human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getsHumanId() {
        return sHumanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.s_human_id
     *
     * @param sHumanId the value for tbl_father_son.s_human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setsHumanId(String sHumanId) {
        this.sHumanId = sHumanId == null ? null : sHumanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.user_id
     *
     * @return the value of tbl_father_son.user_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.user_id
     *
     * @param userId the value for tbl_father_son.user_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.s_sex_div
     *
     * @return the value of tbl_father_son.s_sex_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getsSexDiv() {
        return sSexDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.s_sex_div
     *
     * @param sSexDiv the value for tbl_father_son.s_sex_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setsSexDiv(String sSexDiv) {
        this.sSexDiv = sSexDiv == null ? null : sSexDiv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.delflg
     *
     * @return the value of tbl_father_son.delflg
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.delflg
     *
     * @param delflg the value for tbl_father_son.delflg
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.create_app
     *
     * @return the value of tbl_father_son.create_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.create_app
     *
     * @param createApp the value for tbl_father_son.create_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.create_user
     *
     * @return the value of tbl_father_son.create_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.create_user
     *
     * @param createUser the value for tbl_father_son.create_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.create_dt
     *
     * @return the value of tbl_father_son.create_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.create_dt
     *
     * @param createDt the value for tbl_father_son.create_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.update_app
     *
     * @return the value of tbl_father_son.update_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.update_app
     *
     * @param updateApp the value for tbl_father_son.update_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.update_user
     *
     * @return the value of tbl_father_son.update_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.update_user
     *
     * @param updateUser the value for tbl_father_son.update_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_father_son.update_dt
     *
     * @return the value of tbl_father_son.update_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_father_son.update_dt
     *
     * @param updateDt the value for tbl_father_son.update_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}