package com.bloodnet.model;

import java.util.ArrayList;
import java.util.List;

public class TblHumanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public TblHumanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHumanIdIsNull() {
            addCriterion("human_id is null");
            return (Criteria) this;
        }

        public Criteria andHumanIdIsNotNull() {
            addCriterion("human_id is not null");
            return (Criteria) this;
        }

        public Criteria andHumanIdEqualTo(String value) {
            addCriterion("human_id =", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdNotEqualTo(String value) {
            addCriterion("human_id <>", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdGreaterThan(String value) {
            addCriterion("human_id >", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdGreaterThanOrEqualTo(String value) {
            addCriterion("human_id >=", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdLessThan(String value) {
            addCriterion("human_id <", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdLessThanOrEqualTo(String value) {
            addCriterion("human_id <=", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdLike(String value) {
            addCriterion("human_id like", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdNotLike(String value) {
            addCriterion("human_id not like", value, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdIn(List<String> values) {
            addCriterion("human_id in", values, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdNotIn(List<String> values) {
            addCriterion("human_id not in", values, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdBetween(String value1, String value2) {
            addCriterion("human_id between", value1, value2, "humanId");
            return (Criteria) this;
        }

        public Criteria andHumanIdNotBetween(String value1, String value2) {
            addCriterion("human_id not between", value1, value2, "humanId");
            return (Criteria) this;
        }

        public Criteria andSexDivIsNull() {
            addCriterion("sex_div is null");
            return (Criteria) this;
        }

        public Criteria andSexDivIsNotNull() {
            addCriterion("sex_div is not null");
            return (Criteria) this;
        }

        public Criteria andSexDivEqualTo(String value) {
            addCriterion("sex_div =", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivNotEqualTo(String value) {
            addCriterion("sex_div <>", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivGreaterThan(String value) {
            addCriterion("sex_div >", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivGreaterThanOrEqualTo(String value) {
            addCriterion("sex_div >=", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivLessThan(String value) {
            addCriterion("sex_div <", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivLessThanOrEqualTo(String value) {
            addCriterion("sex_div <=", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivLike(String value) {
            addCriterion("sex_div like", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivNotLike(String value) {
            addCriterion("sex_div not like", value, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivIn(List<String> values) {
            addCriterion("sex_div in", values, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivNotIn(List<String> values) {
            addCriterion("sex_div not in", values, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivBetween(String value1, String value2) {
            addCriterion("sex_div between", value1, value2, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andSexDivNotBetween(String value1, String value2) {
            addCriterion("sex_div not between", value1, value2, "sexDiv");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameIsNull() {
            addCriterion("user_family_name is null");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameIsNotNull() {
            addCriterion("user_family_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEqualTo(String value) {
            addCriterion("user_family_name =", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameNotEqualTo(String value) {
            addCriterion("user_family_name <>", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameGreaterThan(String value) {
            addCriterion("user_family_name >", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_family_name >=", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameLessThan(String value) {
            addCriterion("user_family_name <", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameLessThanOrEqualTo(String value) {
            addCriterion("user_family_name <=", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameLike(String value) {
            addCriterion("user_family_name like", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameNotLike(String value) {
            addCriterion("user_family_name not like", value, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameIn(List<String> values) {
            addCriterion("user_family_name in", values, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameNotIn(List<String> values) {
            addCriterion("user_family_name not in", values, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameBetween(String value1, String value2) {
            addCriterion("user_family_name between", value1, value2, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameNotBetween(String value1, String value2) {
            addCriterion("user_family_name not between", value1, value2, "userFamilyName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameIsNull() {
            addCriterion("user_first_name is null");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameIsNotNull() {
            addCriterion("user_first_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEqualTo(String value) {
            addCriterion("user_first_name =", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameNotEqualTo(String value) {
            addCriterion("user_first_name <>", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameGreaterThan(String value) {
            addCriterion("user_first_name >", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_first_name >=", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameLessThan(String value) {
            addCriterion("user_first_name <", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameLessThanOrEqualTo(String value) {
            addCriterion("user_first_name <=", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameLike(String value) {
            addCriterion("user_first_name like", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameNotLike(String value) {
            addCriterion("user_first_name not like", value, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameIn(List<String> values) {
            addCriterion("user_first_name in", values, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameNotIn(List<String> values) {
            addCriterion("user_first_name not in", values, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameBetween(String value1, String value2) {
            addCriterion("user_first_name between", value1, value2, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameNotBetween(String value1, String value2) {
            addCriterion("user_first_name not between", value1, value2, "userFirstName");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngIsNull() {
            addCriterion("user_family_name_eng is null");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngIsNotNull() {
            addCriterion("user_family_name_eng is not null");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngEqualTo(String value) {
            addCriterion("user_family_name_eng =", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngNotEqualTo(String value) {
            addCriterion("user_family_name_eng <>", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngGreaterThan(String value) {
            addCriterion("user_family_name_eng >", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngGreaterThanOrEqualTo(String value) {
            addCriterion("user_family_name_eng >=", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngLessThan(String value) {
            addCriterion("user_family_name_eng <", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngLessThanOrEqualTo(String value) {
            addCriterion("user_family_name_eng <=", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngLike(String value) {
            addCriterion("user_family_name_eng like", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngNotLike(String value) {
            addCriterion("user_family_name_eng not like", value, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngIn(List<String> values) {
            addCriterion("user_family_name_eng in", values, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngNotIn(List<String> values) {
            addCriterion("user_family_name_eng not in", values, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngBetween(String value1, String value2) {
            addCriterion("user_family_name_eng between", value1, value2, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFamilyNameEngNotBetween(String value1, String value2) {
            addCriterion("user_family_name_eng not between", value1, value2, "userFamilyNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngIsNull() {
            addCriterion("user_first_name_eng is null");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngIsNotNull() {
            addCriterion("user_first_name_eng is not null");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngEqualTo(String value) {
            addCriterion("user_first_name_eng =", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngNotEqualTo(String value) {
            addCriterion("user_first_name_eng <>", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngGreaterThan(String value) {
            addCriterion("user_first_name_eng >", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngGreaterThanOrEqualTo(String value) {
            addCriterion("user_first_name_eng >=", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngLessThan(String value) {
            addCriterion("user_first_name_eng <", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngLessThanOrEqualTo(String value) {
            addCriterion("user_first_name_eng <=", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngLike(String value) {
            addCriterion("user_first_name_eng like", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngNotLike(String value) {
            addCriterion("user_first_name_eng not like", value, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngIn(List<String> values) {
            addCriterion("user_first_name_eng in", values, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngNotIn(List<String> values) {
            addCriterion("user_first_name_eng not in", values, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngBetween(String value1, String value2) {
            addCriterion("user_first_name_eng between", value1, value2, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserFirstNameEngNotBetween(String value1, String value2) {
            addCriterion("user_first_name_eng not between", value1, value2, "userFirstNameEng");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoIsNull() {
            addCriterion("user_image_file_no is null");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoIsNotNull() {
            addCriterion("user_image_file_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoEqualTo(String value) {
            addCriterion("user_image_file_no =", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoNotEqualTo(String value) {
            addCriterion("user_image_file_no <>", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoGreaterThan(String value) {
            addCriterion("user_image_file_no >", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoGreaterThanOrEqualTo(String value) {
            addCriterion("user_image_file_no >=", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoLessThan(String value) {
            addCriterion("user_image_file_no <", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoLessThanOrEqualTo(String value) {
            addCriterion("user_image_file_no <=", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoLike(String value) {
            addCriterion("user_image_file_no like", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoNotLike(String value) {
            addCriterion("user_image_file_no not like", value, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoIn(List<String> values) {
            addCriterion("user_image_file_no in", values, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoNotIn(List<String> values) {
            addCriterion("user_image_file_no not in", values, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoBetween(String value1, String value2) {
            addCriterion("user_image_file_no between", value1, value2, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andUserImageFileNoNotBetween(String value1, String value2) {
            addCriterion("user_image_file_no not between", value1, value2, "userImageFileNo");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNull() {
            addCriterion("birthdate is null");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNotNull() {
            addCriterion("birthdate is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdateEqualTo(String value) {
            addCriterion("birthdate =", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotEqualTo(String value) {
            addCriterion("birthdate <>", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThan(String value) {
            addCriterion("birthdate >", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThanOrEqualTo(String value) {
            addCriterion("birthdate >=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThan(String value) {
            addCriterion("birthdate <", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThanOrEqualTo(String value) {
            addCriterion("birthdate <=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLike(String value) {
            addCriterion("birthdate like", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotLike(String value) {
            addCriterion("birthdate not like", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateIn(List<String> values) {
            addCriterion("birthdate in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotIn(List<String> values) {
            addCriterion("birthdate not in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateBetween(String value1, String value2) {
            addCriterion("birthdate between", value1, value2, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotBetween(String value1, String value2) {
            addCriterion("birthdate not between", value1, value2, "birthdate");
            return (Criteria) this;
        }

        public Criteria andDeathDateIsNull() {
            addCriterion("death_date is null");
            return (Criteria) this;
        }

        public Criteria andDeathDateIsNotNull() {
            addCriterion("death_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeathDateEqualTo(String value) {
            addCriterion("death_date =", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateNotEqualTo(String value) {
            addCriterion("death_date <>", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateGreaterThan(String value) {
            addCriterion("death_date >", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateGreaterThanOrEqualTo(String value) {
            addCriterion("death_date >=", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateLessThan(String value) {
            addCriterion("death_date <", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateLessThanOrEqualTo(String value) {
            addCriterion("death_date <=", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateLike(String value) {
            addCriterion("death_date like", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateNotLike(String value) {
            addCriterion("death_date not like", value, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateIn(List<String> values) {
            addCriterion("death_date in", values, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateNotIn(List<String> values) {
            addCriterion("death_date not in", values, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateBetween(String value1, String value2) {
            addCriterion("death_date between", value1, value2, "deathDate");
            return (Criteria) this;
        }

        public Criteria andDeathDateNotBetween(String value1, String value2) {
            addCriterion("death_date not between", value1, value2, "deathDate");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("ID_number is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("ID_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("ID_number =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("ID_number <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("ID_number >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("ID_number >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("ID_number <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("ID_number <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("ID_number like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("ID_number not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("ID_number in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("ID_number not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("ID_number between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("ID_number not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andDynastyIsNull() {
            addCriterion("dynasty is null");
            return (Criteria) this;
        }

        public Criteria andDynastyIsNotNull() {
            addCriterion("dynasty is not null");
            return (Criteria) this;
        }

        public Criteria andDynastyEqualTo(String value) {
            addCriterion("dynasty =", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyNotEqualTo(String value) {
            addCriterion("dynasty <>", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyGreaterThan(String value) {
            addCriterion("dynasty >", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyGreaterThanOrEqualTo(String value) {
            addCriterion("dynasty >=", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyLessThan(String value) {
            addCriterion("dynasty <", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyLessThanOrEqualTo(String value) {
            addCriterion("dynasty <=", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyLike(String value) {
            addCriterion("dynasty like", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyNotLike(String value) {
            addCriterion("dynasty not like", value, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyIn(List<String> values) {
            addCriterion("dynasty in", values, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyNotIn(List<String> values) {
            addCriterion("dynasty not in", values, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyBetween(String value1, String value2) {
            addCriterion("dynasty between", value1, value2, "dynasty");
            return (Criteria) this;
        }

        public Criteria andDynastyNotBetween(String value1, String value2) {
            addCriterion("dynasty not between", value1, value2, "dynasty");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andWorkDivIsNull() {
            addCriterion("work_div is null");
            return (Criteria) this;
        }

        public Criteria andWorkDivIsNotNull() {
            addCriterion("work_div is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDivEqualTo(String value) {
            addCriterion("work_div =", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivNotEqualTo(String value) {
            addCriterion("work_div <>", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivGreaterThan(String value) {
            addCriterion("work_div >", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivGreaterThanOrEqualTo(String value) {
            addCriterion("work_div >=", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivLessThan(String value) {
            addCriterion("work_div <", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivLessThanOrEqualTo(String value) {
            addCriterion("work_div <=", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivLike(String value) {
            addCriterion("work_div like", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivNotLike(String value) {
            addCriterion("work_div not like", value, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivIn(List<String> values) {
            addCriterion("work_div in", values, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivNotIn(List<String> values) {
            addCriterion("work_div not in", values, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivBetween(String value1, String value2) {
            addCriterion("work_div between", value1, value2, "workDiv");
            return (Criteria) this;
        }

        public Criteria andWorkDivNotBetween(String value1, String value2) {
            addCriterion("work_div not between", value1, value2, "workDiv");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNull() {
            addCriterion("province_code is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIsNotNull() {
            addCriterion("province_code is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeEqualTo(String value) {
            addCriterion("province_code =", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotEqualTo(String value) {
            addCriterion("province_code <>", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThan(String value) {
            addCriterion("province_code >", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("province_code >=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThan(String value) {
            addCriterion("province_code <", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLessThanOrEqualTo(String value) {
            addCriterion("province_code <=", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeLike(String value) {
            addCriterion("province_code like", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotLike(String value) {
            addCriterion("province_code not like", value, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeIn(List<String> values) {
            addCriterion("province_code in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotIn(List<String> values) {
            addCriterion("province_code not in", values, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeBetween(String value1, String value2) {
            addCriterion("province_code between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andProvinceCodeNotBetween(String value1, String value2) {
            addCriterion("province_code not between", value1, value2, "provinceCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNull() {
            addCriterion("city_code is null");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNotNull() {
            addCriterion("city_code is not null");
            return (Criteria) this;
        }

        public Criteria andCityCodeEqualTo(String value) {
            addCriterion("city_code =", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotEqualTo(String value) {
            addCriterion("city_code <>", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThan(String value) {
            addCriterion("city_code >", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("city_code >=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThan(String value) {
            addCriterion("city_code <", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThanOrEqualTo(String value) {
            addCriterion("city_code <=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLike(String value) {
            addCriterion("city_code like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotLike(String value) {
            addCriterion("city_code not like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeIn(List<String> values) {
            addCriterion("city_code in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotIn(List<String> values) {
            addCriterion("city_code not in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeBetween(String value1, String value2) {
            addCriterion("city_code between", value1, value2, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotBetween(String value1, String value2) {
            addCriterion("city_code not between", value1, value2, "cityCode");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNull() {
            addCriterion("address1 is null");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNotNull() {
            addCriterion("address1 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress1EqualTo(String value) {
            addCriterion("address1 =", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotEqualTo(String value) {
            addCriterion("address1 <>", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThan(String value) {
            addCriterion("address1 >", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("address1 >=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThan(String value) {
            addCriterion("address1 <", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThanOrEqualTo(String value) {
            addCriterion("address1 <=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Like(String value) {
            addCriterion("address1 like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotLike(String value) {
            addCriterion("address1 not like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1In(List<String> values) {
            addCriterion("address1 in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotIn(List<String> values) {
            addCriterion("address1 not in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Between(String value1, String value2) {
            addCriterion("address1 between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotBetween(String value1, String value2) {
            addCriterion("address1 not between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNull() {
            addCriterion("address2 is null");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNotNull() {
            addCriterion("address2 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress2EqualTo(String value) {
            addCriterion("address2 =", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotEqualTo(String value) {
            addCriterion("address2 <>", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThan(String value) {
            addCriterion("address2 >", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("address2 >=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThan(String value) {
            addCriterion("address2 <", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThanOrEqualTo(String value) {
            addCriterion("address2 <=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Like(String value) {
            addCriterion("address2 like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotLike(String value) {
            addCriterion("address2 not like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2In(List<String> values) {
            addCriterion("address2 in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotIn(List<String> values) {
            addCriterion("address2 not in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Between(String value1, String value2) {
            addCriterion("address2 between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotBetween(String value1, String value2) {
            addCriterion("address2 not between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andDelflgIsNull() {
            addCriterion("delflg is null");
            return (Criteria) this;
        }

        public Criteria andDelflgIsNotNull() {
            addCriterion("delflg is not null");
            return (Criteria) this;
        }

        public Criteria andDelflgEqualTo(Boolean value) {
            addCriterion("delflg =", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgNotEqualTo(Boolean value) {
            addCriterion("delflg <>", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgGreaterThan(Boolean value) {
            addCriterion("delflg >", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delflg >=", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgLessThan(Boolean value) {
            addCriterion("delflg <", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgLessThanOrEqualTo(Boolean value) {
            addCriterion("delflg <=", value, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgIn(List<Boolean> values) {
            addCriterion("delflg in", values, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgNotIn(List<Boolean> values) {
            addCriterion("delflg not in", values, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgBetween(Boolean value1, Boolean value2) {
            addCriterion("delflg between", value1, value2, "delflg");
            return (Criteria) this;
        }

        public Criteria andDelflgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delflg not between", value1, value2, "delflg");
            return (Criteria) this;
        }

        public Criteria andCreateAppIsNull() {
            addCriterion("create_app is null");
            return (Criteria) this;
        }

        public Criteria andCreateAppIsNotNull() {
            addCriterion("create_app is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAppEqualTo(String value) {
            addCriterion("create_app =", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotEqualTo(String value) {
            addCriterion("create_app <>", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppGreaterThan(String value) {
            addCriterion("create_app >", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppGreaterThanOrEqualTo(String value) {
            addCriterion("create_app >=", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppLessThan(String value) {
            addCriterion("create_app <", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppLessThanOrEqualTo(String value) {
            addCriterion("create_app <=", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppLike(String value) {
            addCriterion("create_app like", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotLike(String value) {
            addCriterion("create_app not like", value, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppIn(List<String> values) {
            addCriterion("create_app in", values, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotIn(List<String> values) {
            addCriterion("create_app not in", values, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppBetween(String value1, String value2) {
            addCriterion("create_app between", value1, value2, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateAppNotBetween(String value1, String value2) {
            addCriterion("create_app not between", value1, value2, "createApp");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNull() {
            addCriterion("create_dt is null");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNotNull() {
            addCriterion("create_dt is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDtEqualTo(String value) {
            addCriterion("create_dt =", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotEqualTo(String value) {
            addCriterion("create_dt <>", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThan(String value) {
            addCriterion("create_dt >", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThanOrEqualTo(String value) {
            addCriterion("create_dt >=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThan(String value) {
            addCriterion("create_dt <", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThanOrEqualTo(String value) {
            addCriterion("create_dt <=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLike(String value) {
            addCriterion("create_dt like", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotLike(String value) {
            addCriterion("create_dt not like", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtIn(List<String> values) {
            addCriterion("create_dt in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotIn(List<String> values) {
            addCriterion("create_dt not in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtBetween(String value1, String value2) {
            addCriterion("create_dt between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotBetween(String value1, String value2) {
            addCriterion("create_dt not between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("update_app is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("update_app is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("update_app =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("update_app <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("update_app >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("update_app >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("update_app <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("update_app <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("update_app like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("update_app not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("update_app in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("update_app not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("update_app between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("update_app not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIsNull() {
            addCriterion("update_dt is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIsNotNull() {
            addCriterion("update_dt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDtEqualTo(String value) {
            addCriterion("update_dt =", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotEqualTo(String value) {
            addCriterion("update_dt <>", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtGreaterThan(String value) {
            addCriterion("update_dt >", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtGreaterThanOrEqualTo(String value) {
            addCriterion("update_dt >=", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLessThan(String value) {
            addCriterion("update_dt <", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLessThanOrEqualTo(String value) {
            addCriterion("update_dt <=", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtLike(String value) {
            addCriterion("update_dt like", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotLike(String value) {
            addCriterion("update_dt not like", value, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtIn(List<String> values) {
            addCriterion("update_dt in", values, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotIn(List<String> values) {
            addCriterion("update_dt not in", values, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtBetween(String value1, String value2) {
            addCriterion("update_dt between", value1, value2, "updateDt");
            return (Criteria) this;
        }

        public Criteria andUpdateDtNotBetween(String value1, String value2) {
            addCriterion("update_dt not between", value1, value2, "updateDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_human
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 24 18:18:32 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_human
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}