package com.bloodnet.model;

public class TblHuman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String humanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.sex_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String sexDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.user_family_name
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String userFamilyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.user_first_name
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String userFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.user_family_name_eng
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String userFamilyNameEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.user_first_name_eng
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String userFirstNameEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.user_image_file_no
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String userImageFileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.birthdate
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.death_date
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String deathDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.ID_number
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.country
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.dynasty
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String dynasty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.email
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.work_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String workDiv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.province_code
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.city_code
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.address1
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.address2
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.delflg
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private Boolean delflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.create_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.create_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.create_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.update_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.update_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_human.update_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.human_id
     *
     * @return the value of tbl_human.human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getHumanId() {
        return humanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.human_id
     *
     * @param humanId the value for tbl_human.human_id
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setHumanId(String humanId) {
        this.humanId = humanId == null ? null : humanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.sex_div
     *
     * @return the value of tbl_human.sex_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getSexDiv() {
        return sexDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.sex_div
     *
     * @param sexDiv the value for tbl_human.sex_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setSexDiv(String sexDiv) {
        this.sexDiv = sexDiv == null ? null : sexDiv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.user_family_name
     *
     * @return the value of tbl_human.user_family_name
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUserFamilyName() {
        return userFamilyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.user_family_name
     *
     * @param userFamilyName the value for tbl_human.user_family_name
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUserFamilyName(String userFamilyName) {
        this.userFamilyName = userFamilyName == null ? null : userFamilyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.user_first_name
     *
     * @return the value of tbl_human.user_first_name
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUserFirstName() {
        return userFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.user_first_name
     *
     * @param userFirstName the value for tbl_human.user_first_name
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUserFirstName(String userFirstName) {
        this.userFirstName = userFirstName == null ? null : userFirstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.user_family_name_eng
     *
     * @return the value of tbl_human.user_family_name_eng
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUserFamilyNameEng() {
        return userFamilyNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.user_family_name_eng
     *
     * @param userFamilyNameEng the value for tbl_human.user_family_name_eng
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUserFamilyNameEng(String userFamilyNameEng) {
        this.userFamilyNameEng = userFamilyNameEng == null ? null : userFamilyNameEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.user_first_name_eng
     *
     * @return the value of tbl_human.user_first_name_eng
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUserFirstNameEng() {
        return userFirstNameEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.user_first_name_eng
     *
     * @param userFirstNameEng the value for tbl_human.user_first_name_eng
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUserFirstNameEng(String userFirstNameEng) {
        this.userFirstNameEng = userFirstNameEng == null ? null : userFirstNameEng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.user_image_file_no
     *
     * @return the value of tbl_human.user_image_file_no
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUserImageFileNo() {
        return userImageFileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.user_image_file_no
     *
     * @param userImageFileNo the value for tbl_human.user_image_file_no
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUserImageFileNo(String userImageFileNo) {
        this.userImageFileNo = userImageFileNo == null ? null : userImageFileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.birthdate
     *
     * @return the value of tbl_human.birthdate
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.birthdate
     *
     * @param birthdate the value for tbl_human.birthdate
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate == null ? null : birthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.death_date
     *
     * @return the value of tbl_human.death_date
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getDeathDate() {
        return deathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.death_date
     *
     * @param deathDate the value for tbl_human.death_date
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setDeathDate(String deathDate) {
        this.deathDate = deathDate == null ? null : deathDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.ID_number
     *
     * @return the value of tbl_human.ID_number
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.ID_number
     *
     * @param idNumber the value for tbl_human.ID_number
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.country
     *
     * @return the value of tbl_human.country
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.country
     *
     * @param country the value for tbl_human.country
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.dynasty
     *
     * @return the value of tbl_human.dynasty
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.dynasty
     *
     * @param dynasty the value for tbl_human.dynasty
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty == null ? null : dynasty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.email
     *
     * @return the value of tbl_human.email
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.email
     *
     * @param email the value for tbl_human.email
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.work_div
     *
     * @return the value of tbl_human.work_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getWorkDiv() {
        return workDiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.work_div
     *
     * @param workDiv the value for tbl_human.work_div
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setWorkDiv(String workDiv) {
        this.workDiv = workDiv == null ? null : workDiv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.province_code
     *
     * @return the value of tbl_human.province_code
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.province_code
     *
     * @param provinceCode the value for tbl_human.province_code
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.city_code
     *
     * @return the value of tbl_human.city_code
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.city_code
     *
     * @param cityCode the value for tbl_human.city_code
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.address1
     *
     * @return the value of tbl_human.address1
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.address1
     *
     * @param address1 the value for tbl_human.address1
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.address2
     *
     * @return the value of tbl_human.address2
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.address2
     *
     * @param address2 the value for tbl_human.address2
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.delflg
     *
     * @return the value of tbl_human.delflg
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public Boolean getDelflg() {
        return delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.delflg
     *
     * @param delflg the value for tbl_human.delflg
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setDelflg(Boolean delflg) {
        this.delflg = delflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.create_app
     *
     * @return the value of tbl_human.create_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.create_app
     *
     * @param createApp the value for tbl_human.create_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.create_user
     *
     * @return the value of tbl_human.create_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.create_user
     *
     * @param createUser the value for tbl_human.create_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.create_dt
     *
     * @return the value of tbl_human.create_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.create_dt
     *
     * @param createDt the value for tbl_human.create_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.update_app
     *
     * @return the value of tbl_human.update_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.update_app
     *
     * @param updateApp the value for tbl_human.update_app
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.update_user
     *
     * @return the value of tbl_human.update_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.update_user
     *
     * @param updateUser the value for tbl_human.update_user
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_human.update_dt
     *
     * @return the value of tbl_human.update_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_human.update_dt
     *
     * @param updateDt the value for tbl_human.update_dt
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}