package com.bloodnet.model;

public class TblSeq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.function_code
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String functionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.div_code
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String divCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.no
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.initial_value
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private Integer initialValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.increment_value
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private Integer incrementValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.length
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.create_app
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String createApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.create_user
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.create_dt
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.update_app
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String updateApp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.update_user
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seq.update_dt
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    private String updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.function_code
     *
     * @return the value of tbl_seq.function_code
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.function_code
     *
     * @param functionCode the value for tbl_seq.function_code
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode == null ? null : functionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.div_code
     *
     * @return the value of tbl_seq.div_code
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getDivCode() {
        return divCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.div_code
     *
     * @param divCode the value for tbl_seq.div_code
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setDivCode(String divCode) {
        this.divCode = divCode == null ? null : divCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.no
     *
     * @return the value of tbl_seq.no
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.no
     *
     * @param no the value for tbl_seq.no
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.initial_value
     *
     * @return the value of tbl_seq.initial_value
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public Integer getInitialValue() {
        return initialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.initial_value
     *
     * @param initialValue the value for tbl_seq.initial_value
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setInitialValue(Integer initialValue) {
        this.initialValue = initialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.increment_value
     *
     * @return the value of tbl_seq.increment_value
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public Integer getIncrementValue() {
        return incrementValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.increment_value
     *
     * @param incrementValue the value for tbl_seq.increment_value
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setIncrementValue(Integer incrementValue) {
        this.incrementValue = incrementValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.length
     *
     * @return the value of tbl_seq.length
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.length
     *
     * @param length the value for tbl_seq.length
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.create_app
     *
     * @return the value of tbl_seq.create_app
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getCreateApp() {
        return createApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.create_app
     *
     * @param createApp the value for tbl_seq.create_app
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setCreateApp(String createApp) {
        this.createApp = createApp == null ? null : createApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.create_user
     *
     * @return the value of tbl_seq.create_user
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.create_user
     *
     * @param createUser the value for tbl_seq.create_user
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.create_dt
     *
     * @return the value of tbl_seq.create_dt
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.create_dt
     *
     * @param createDt the value for tbl_seq.create_dt
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setCreateDt(String createDt) {
        this.createDt = createDt == null ? null : createDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.update_app
     *
     * @return the value of tbl_seq.update_app
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.update_app
     *
     * @param updateApp the value for tbl_seq.update_app
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp == null ? null : updateApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.update_user
     *
     * @return the value of tbl_seq.update_user
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.update_user
     *
     * @param updateUser the value for tbl_seq.update_user
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seq.update_dt
     *
     * @return the value of tbl_seq.update_dt
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public String getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seq.update_dt
     *
     * @param updateDt the value for tbl_seq.update_dt
     *
     * @mbggenerated Fri Apr 07 15:03:38 JST 2017
     */
    public void setUpdateDt(String updateDt) {
        this.updateDt = updateDt == null ? null : updateDt.trim();
    }
}