package com.bloodnet.mappers;

import com.bloodnet.model.TblFatherSon;
import com.bloodnet.model.TblFatherSonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblFatherSonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_father_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int countByExample(TblFatherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_father_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int deleteByExample(TblFatherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_father_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int insert(TblFatherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_father_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int insertSelective(TblFatherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_father_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    List<TblFatherSon> selectByExample(TblFatherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_father_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblFatherSon record, @Param("example") TblFatherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_father_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int updateByExample(@Param("record") TblFatherSon record, @Param("example") TblFatherSonExample example);
}