package com.bloodnet.mappers;

import com.bloodnet.model.TblMotherSon;
import com.bloodnet.model.TblMotherSonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblMotherSonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mother_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int countByExample(TblMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mother_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int deleteByExample(TblMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mother_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int insert(TblMotherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mother_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int insertSelective(TblMotherSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mother_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    List<TblMotherSon> selectByExample(TblMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mother_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblMotherSon record, @Param("example") TblMotherSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mother_son
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int updateByExample(@Param("record") TblMotherSon record, @Param("example") TblMotherSonExample example);
}