package com.bloodnet.mappers;

import com.bloodnet.model.TblProfile;
import com.bloodnet.model.TblProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_profile
     *
     * @mbggenerated Fri Apr 07 16:00:45 JST 2017
     */
    int countByExample(TblProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_profile
     *
     * @mbggenerated Fri Apr 07 16:00:45 JST 2017
     */
    int deleteByExample(TblProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_profile
     *
     * @mbggenerated Fri Apr 07 16:00:45 JST 2017
     */
    int insert(TblProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_profile
     *
     * @mbggenerated Fri Apr 07 16:00:45 JST 2017
     */
    int insertSelective(TblProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_profile
     *
     * @mbggenerated Fri Apr 07 16:00:45 JST 2017
     */
    List<TblProfile> selectByExample(TblProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_profile
     *
     * @mbggenerated Fri Apr 07 16:00:45 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblProfile record, @Param("example") TblProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_profile
     *
     * @mbggenerated Fri Apr 07 16:00:45 JST 2017
     */
    int updateByExample(@Param("record") TblProfile record, @Param("example") TblProfileExample example);
}