package com.bloodnet.mappers;

import com.bloodnet.model.TblRelationSpouse;
import com.bloodnet.model.TblRelationSpouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblRelationSpouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_spouse
     *
     * @mbggenerated Fri Apr 07 18:36:16 JST 2017
     */
    int countByExample(TblRelationSpouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_spouse
     *
     * @mbggenerated Fri Apr 07 18:36:16 JST 2017
     */
    int deleteByExample(TblRelationSpouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_spouse
     *
     * @mbggenerated Fri Apr 07 18:36:16 JST 2017
     */
    int insert(TblRelationSpouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_spouse
     *
     * @mbggenerated Fri Apr 07 18:36:16 JST 2017
     */
    int insertSelective(TblRelationSpouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_spouse
     *
     * @mbggenerated Fri Apr 07 18:36:16 JST 2017
     */
    List<TblRelationSpouse> selectByExample(TblRelationSpouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_spouse
     *
     * @mbggenerated Fri Apr 07 18:36:16 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblRelationSpouse record, @Param("example") TblRelationSpouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_relation_spouse
     *
     * @mbggenerated Fri Apr 07 18:36:16 JST 2017
     */
    int updateByExample(@Param("record") TblRelationSpouse record, @Param("example") TblRelationSpouseExample example);
}