package com.bloodnet.mappers;

import com.bloodnet.model.TblSeq;
import com.bloodnet.model.TblSeqExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seq
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int countByExample(TblSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seq
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int deleteByExample(TblSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seq
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int insert(TblSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seq
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int insertSelective(TblSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seq
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    List<TblSeq> selectByExample(TblSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seq
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int updateByExampleSelective(@Param("record") TblSeq record, @Param("example") TblSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seq
     *
     * @mbggenerated Fri Mar 24 18:18:32 JST 2017
     */
    int updateByExample(@Param("record") TblSeq record, @Param("example") TblSeqExample example);
}